# EditorConfig テスト用 YAML ファイル
# EditorConfigが正しく動作する場合、このファイルは2スペースインデントになります

project:
  name: operase
  description: EditorConfigテストプロジェクト
  version: 1.0.0

editorconfig:
  enabled: true
  settings:
    indent:
      style: space
      size: 2
    encoding: utf-8
    end_of_line: lf
    insert_final_newline: true
    trim_trailing_whitespace: true

languages:
  - name: JavaScript
    extension: .js
    indent_size: 2
  - name: Python
    extension: .py
    indent_size: 4
  - name: YAML
    extension: .yml
    indent_size: 2
  - name: JSON
    extension: .json
    indent_size: 2

features:
  auto_indent: true
  trailing_space_removal: true
  final_newline: true
  charset_detection: true